
/*! forms.js — Google Apps Script endpoint (UTF-8, replyTo, redirect) */
const ENDPOINT_URL = "PASTE_YOUR_DEPLOYED_APPS_SCRIPT_URL_HERE"; // ضع رابط Web App هنا
function showToast(m,e=false){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText="position:fixed;inset-inline-start:50%;transform:translateX(-50%);bottom:18px;background:linear-gradient(to left,#714984,#523663);color:#fff;padding:12px 16px;border-radius:12px;box-shadow:0 10px 24px rgba(0,0,0,.18);display:none;z-index:9999;font-family:'Cairo',sans-serif";document.body.appendChild(t);}t.style.background=e?'#b3261e':'linear-gradient(to left,#714984,#523663)';t.textContent=m;t.style.display='block';setTimeout(()=>{t.style.display='none';},2600);}
function normalizeConstraints(f){['name','message'].forEach(n=>f.querySelectorAll(`[name="${n}"]`).forEach(el=>el.setAttribute('required','')));f.querySelectorAll('input[name="email"]').forEach(el=>{el.type='email';el.setAttribute('inputmode','email');});f.querySelectorAll('input[name="phone"]').forEach(el=>{el.type='tel';el.setAttribute('pattern','\\+?\\d[\\d\\s\\-]{6,}');});if(!f.hasAttribute('accept-charset'))f.setAttribute('accept-charset','UTF-8');}
function validateForm(f){normalizeConstraints(f);if(!f.checkValidity()){f.reportValidity();showToast("رجاءً أكمل الحقول المطلوبة.",true);return false;}const email=f.querySelector('[name="email"]');if(email&&email.value&&!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email.value)){email.focus();showToast("صيغة البريد الإلكتروني غير صحيحة.",true);return false;}return true;}
function getThankYouUrl(){const {origin,pathname}=window.location;const parts=pathname.split('/').filter(Boolean);parts.pop();const base='/' + parts.join('/') + '/';return origin + base + 'thankyou.html';}
function attachReplyTo(f){const email=f.querySelector('[name="email"]');if(email&&email.value&&!f.querySelector('[name="_replyto"]')){const i=document.createElement('input');i.type='hidden';i.name='_replyto';i.value=email.value;f.appendChild(i);}}
async function submitAjaxForm(ev){ev.preventDefault();const f=ev.target;if(!validateForm(f))return;if(!ENDPOINT_URL||ENDPOINT_URL.includes("PASTE_YOUR_DEPLOYED")){showToast("لم يتم إعداد نقطة الإرسال بعد. يرجى تهيئة الرابط في forms.js",true);return;}const hp=f.querySelector('input[name="website"], input[name="hp"]');if(hp&&hp.value.trim()!==""){showToast("تم رفض الإرسال (spambot).",true);return;}attachReplyTo(f);const btn=f.querySelector('button[type="submit"], input[type="submit"]');const o=btn?(btn.innerText||btn.value):null;if(btn){btn.disabled=true;if(btn.innerText){btn.innerText="جارٍ الإرسال…";}else if(btn.value){btn.value="جارٍ الإرسال…";}}try{const fd=new FormData(f);fd.append("_source_page",location.pathname.replace(/^.*\\//,''));fd.append("_timestamp",new Date().toISOString());await fetch(ENDPOINT_URL,{method:"POST",mode:"no-cors",body:fd});showToast("تم الاستلام بنجاح. شكرًا لك!");f.reset();setTimeout(()=>{window.location.replace(getThankYouUrl());},900);}catch(err){console.error(err);showToast("تعذّر الإرسال، حاول لاحقًا.",true);}finally{if(btn){btn.disabled=false;if(o!==null){if(btn.innerText!==undefined){btn.innerText=o;}else{btn.value=o;}}}}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('form').forEach(f=>{if(!f.classList.contains('js-ajax-form'))f.classList.add('js-ajax-form');f.addEventListener('submit',submitAjaxForm);});});
